version: '3.8'

services:
  # Aplicación Node.js
  backend:
    build: .
    container_name: costos_backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - JWT_SECRET=tu_clave_secreta_super_segura
      - SUPABASE_URL=https://vbhqfopxljjuxpsnlsuv.supabase.co
      - SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZiaHFmb3B4bGpqdXhwc25sc3V2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzNDU3NDcsImV4cCI6MjA1NzkyMTc0N30.H-I-R_CmFi4Jaft-OTHjuKJ7Eu9DGUWy6h_wIBq4dV4
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  costos_network:
    driver: bridge 